### ISSUE TITLE
Blank text sent when there's a colon in the text.

### ISSUE THREAD

**Issue by darrin** [trejonh/Furious-Monkey#7]
Awesome little lib! Thanks for writing it you saved me some time. I did find one problem.

I was trying to send a link via text and found that it wouldn't send unless I removed the link. I made a lucky guess that it was the colon. Turns out [these people](https://stackoverflow.com/questions/11796664/smtplib-sends-blank-message-if-the-message-contain-certain-characters)  ran into this [as did these](https://stackoverflow.com/questions/7294885/python-emailing-use-of-colon-causes-no-output) - which gave me some clues. 

I found that if I changed this bit of code:
`		message = "From: <Furious-Monkey>nonreply@foo.com\n"+"To: "+email_data["recipients"]+"\nSubject: "+email_data["subject"]+"\n"+email_data["message"]+"\n"
`

to add an extra newline prior to appending the message :
`		message = "From: <Furious-Monkey>nonreply@foo.com\n"+"To: "+email_data["recipients"]+"\nSubject: "+email_data["subject"]+"\n\n"+email_data["message"]+"\n"
`

Everything started working.

Another workaround is to prepend a newline to the message which is what I did since I wanted to use the official version of the library.

**Comment by trejonh** [comment]
Great catch, thank you. I will make the appropriate fix @darrin

**Comment by darrin** [comment]
Course! Sorry I was too lazy for the pull request. ;)

**Comment by trejonh** [comment]
@darrin It is now patched and published to npm

**Comment by darrin** [comment]
Awesome! Thanks!
